=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
Date: 17-02-2016
created by: Priyanka Patil
=end

class Fibonacci
  def fibonacci_series
  	number= 4000000
 	puts "Fibonacci Series : "
 	num1=1
 	num2=2
 	sum=0
 	even_sum=0
 	puts num1
	puts num2
 	while sum<number do
 	  sum= num1+num2
 	  puts sum
 	  if sum%2 == 0
 	  	even_sum+= sum
 	  end
 	  num1=num2
 	  num2=sum
 	end
 	puts "sum of even valued terms is : #{even_sum}"
  end
end
series=Fibonacci.new
series.fibonacci_series